fix typo
thedataengineeringbook/thedataengineeringbook pull request #58
Opened 2022-10-22 16:44 UTC by tumit

- ดูและ => ดูแล

ผมเข้าใจว่า ๆ ใช้กรณีออกเสียงซ้ำ แต่ 2 อันนี้เป็นคำแยกที่ออกเสียงเดียวเฉย ๆ จะใช้ ๆ ไม่ได้ครับ
- ในที่ๆ เดียว => ในที่ที่เดียว
- หน้าที่ๆ จะต้อง => หน้าที่ที่จะต้อง

2022-10-26 06:10 UTC, zkan approved these changes
โอ้ ขอบคุณมากครับ นี่ผมเพิ่งรู้เลย ปกติใช้ ๆ มาตลอด >_<

2022-10-26 06:11 UTC, zkan requested changes
ขอแก้คำเล็กน้อยครับผม

2022-10-26 06:11 UTC, zkan commented on docs/docs/02-data-engineer.md
> +เราก็มีโอกาศสูงมากที่จะเดินทางผิดพลาด และก่อความเสียหายให้กับองค์กรได้
โอกาศ => โอกาส

2022-10-27 05:38 UTC, zkan commented on docs/docs/02-data-engineer.md
> +เราก็มีโอกาศสูงมากที่จะเดินทางผิดพลาด และก่อความเสียหายให้กับองค์กรได้
@tumit o_O เห็นพี่กด resolve ไป แต่ยังไม่เห็น commit แก้จาก ศ เป็น ส มาครับ อันนี้พี่เผลอกดไปเปล่าครับ 🙇🏼

2022-10-27 08:43 UTC, tumit commented on docs/docs/02-data-engineer.md
> +เราก็มีโอกาศสูงมากที่จะเดินทางผิดพลาด และก่อความเสียหายให้กับองค์กรได้
@zkan สารภาพว่าผมใช้ไม่เป็นครับ 😅 กด resolve แล้วมันไม่ commit ให้ใช่มะ ต้องแก้แล้ว push อีกทีใช่ไหมครับ ?

2022-10-27 18:41 UTC, zkan commented on docs/docs/02-data-engineer.md
> +เราก็มีโอกาศสูงมากที่จะเดินทางผิดพลาด และก่อความเสียหายให้กับองค์กรได้
ฮ่า ๆ ใช่แล้วครับพี่ ต้อง commit ด้วยครับ

2022-10-28 17:48 UTC, zkan commented
@tumit มี conflict ครับ >_< ผมน่าจะ merge ผิดอัน ขออภัยด้วยครับบบ

2022-10-29 15:02 UTC, zkan approved these changes

2022-10-29 15:02 UTC, merged